#!/usr/bin/env python3
"""Sync the page endcap across docs pages.

The endcap is stock Mintlify: a rule, a Columns, and two Cards. It has no
CSS of its own; the site-wide rules in style.css for prose rules and cards
(the yellow line, the outlined cards with the yellow shadow) style it like
every other rule and card on the site.

Two earlier approaches are worth not repeating. A /snippets import does not
survive a web-editor build — the import is stripped and the component renders
as nothing, while its heading still reaches the table of contents, so the
failure reads as a styling bug. Hand-rolled HTML with custom classes did
compile and did reach the DOM, but it looked wrong and needed 329 lines of
CSS to hold together. First-party components need none.

Usage:
    python3 scripts/endcap.py          # sync
    python3 scripts/endcap.py --check  # exit 1 if anything is out of sync

TABS = None puts the endcap on every page in the navigation. To narrow it,
set TABS to a set of tab names and re-run. Idempotent: it adds where the
endcap belongs and removes it where it does not.
"""
import glob
import json
import os
import re
import sys

# None means every tab in docs.json.
TABS = None

SUBSCRIBE_URL = "https://snowdoughnut.com"
AGENCY_URL = "https://snowdoughnut.com/agency"
UTM = "utm_source=docs&utm_medium=owned&utm_campaign=docs-endcap&utm_content="

START = "{/* sd-endcap:start — generated by scripts/endcap.py, do not edit by hand */}"
END = "{/* sd-endcap:end */}"

# Stock Mintlify, nothing else: a rule, Columns, two Cards. No CSS backs any
# of this, no custom class names, no raw HTML. style.css is untouched.
#
# Two equal cards side by side rather than one full-width card above a
# horizontal one. The earlier asymmetric pair looked wrong because the
# cards were different shapes carrying different amounts of text, so
# neither read as finished. Matching shapes with matching copy lengths is
# what makes a default Card look deliberate.
#
# No color prop either. Left alone, Card tints its icon with the theme's
# primary from docs.json, so the brand arrives automatically and both
# cards stay consistent.
#
# Keep both bodies to one short sentence. Cards set their own height from
# the tallest one, so uneven copy leaves visible dead space in the other.
BLOCK = f"""{START}

---

<Columns cols={{2}}>
  <Card title="Get the complete Marketing OS" icon="gift" href="{SUBSCRIBE_URL}?{UTM}os-subscribe" cta="Subscribe for free" arrow>
    Subscribe to Snow Doughnut, our free weekly newsletter, and get every workbook, brief, and checklist here as one connected Notion system.
  </Card>

  <Card title="Have us run it for you" icon="briefcase" href="{AGENCY_URL}?{UTM}agency" cta="Work with us" arrow>
    We implement this system, use it to help you grow and scale, then hand it all off to you when you're ready.
  </Card>
</Columns>

{END}"""

# Matches the current block, and the retired snippet-import form so an older
# checkout is cleaned up rather than ending up with both.
BLOCK_RE = re.compile(re.escape(START) + r".*?" + re.escape(END) + r"\n?", re.S)
LEGACY_RE = re.compile(
    r'^import PageEndcap from "/snippets/page-endcap\.mdx";\n\n|\n*^<PageEndcap />\n?',
    re.M,
)


def tab_names(node, out=None):
    """Collect every tab name in the navigation."""
    out = [] if out is None else out
    if isinstance(node, dict):
        if "tab" in node:
            out.append(node["tab"])
        for value in node.values():
            tab_names(value, out)
    elif isinstance(node, list):
        for item in node:
            tab_names(item, out)
    return out


def slugs_in_tabs(node, wanted, inside=False, out=None):
    """Collect every page slug under a tab whose name is in `wanted`."""
    out = [] if out is None else out
    if isinstance(node, list):
        for item in node:
            if isinstance(item, str):
                if inside:
                    out.append(item)
            else:
                slugs_in_tabs(item, wanted, inside, out)
    elif isinstance(node, dict):
        if "tab" in node:
            inside = node["tab"] in wanted
        for value in node.values():
            if isinstance(value, (list, dict)):
                slugs_in_tabs(value, wanted, inside, out)
    return out


def desired(path, keep):
    src = open(path, encoding="utf-8").read()
    wanted = os.path.splitext(path)[0] in keep
    has_endcap = bool(BLOCK_RE.search(src) or LEGACY_RE.search(src))

    # A page that neither has nor wants an endcap is returned byte for byte.
    # Normalizing it would rewrite the ~137 pages that ship without a trailing
    # newline and bury the real change in whitespace noise.
    if not wanted and not has_endcap:
        return src

    stripped = LEGACY_RE.sub("", BLOCK_RE.sub("", src)).rstrip()
    return stripped + "\n\n" + BLOCK + "\n" if wanted else stripped + "\n"


check = "--check" in sys.argv
config = json.load(open("docs.json", encoding="utf-8"))
tabs = set(tab_names(config["navigation"])) if TABS is None else TABS
keep = {s.lstrip("/") for s in slugs_in_tabs(config["navigation"], tabs)}

stale = []
for path in sorted(glob.glob("*.mdx")):
    current = open(path, encoding="utf-8").read()
    target = desired(path, keep)
    if current == target:
        continue
    stale.append(path)
    if not check:
        open(path, "w", encoding="utf-8").write(target)

verb = "out of sync" if check else "synced"
print(f"endcap on {len(keep)} page(s)")
print(f"{len(stale)} file(s) {verb}" + (": " + ", ".join(stale) if stale else ""))
sys.exit(1 if (check and stale) else 0)
