#!/usr/bin/env python3
"""Sync the page endcap across docs pages.

Why the markup is inlined rather than imported from /snippets:

Mintlify's reusable-snippet import (`import X from "/snippets/x.mdx"`) is not
supported when the site is built through the web editor — the import is
stripped and the component silently renders as nothing. The heading still
reaches the table of contents, which makes the failure look like a styling
bug rather than a missing import. Inlining raw HTML with className is
documented and works in every build path, so the markup lives here instead.

Appearance is still edited in one place: style.css. Only the words live here.

Usage:
    python3 scripts/endcap.py          # sync
    python3 scripts/endcap.py --check  # exit 1 if anything is out of sync

To widen the rollout, add tab names to TABS and re-run. Idempotent: it adds
where the endcap belongs and removes it where it does not.
"""
import glob
import json
import os
import re
import sys

TABS = {"Get started"}

REFERRAL_URL = "https://snowdoughnut.com/refer"
AGENCY_URL = "https://snowdoughnut.com/agency"
UTM = "utm_source=docs&utm_medium=owned&utm_campaign=docs-endcap&utm_content="

START = "{/* sd-endcap:start — generated by scripts/endcap.py, do not edit by hand */}"
END = "{/* sd-endcap:end */}"

BLOCK = f"""{START}

<aside className="sd-endcap" aria-label="More from Snow Doughnut">
  <div className="sd-ad sd-ad-os">
    <div className="sd-ad-inner">
      <p className="sd-eyebrow">Refer 3 friends</p>
      <h2 className="sd-ad-title">Get the complete Marketing OS</h2>
      <p className="sd-ad-copy">Every workbook, brief, checklist, and register on this site, rebuilt in Notion as one connected system. Briefs pull from your positioning. Campaigns inherit your naming conventions. Finished work files itself into the right library.</p>
      <div className="sd-meter">
        <span className="sd-rings" aria-hidden="true"><span className="sd-ring" /><span className="sd-ring" /><span className="sd-ring" /></span>
        <span className="sd-meter-label">Three signups and it's yours. That's the whole price.</span>
      </div>
      <a className="sd-cta" href="{REFERRAL_URL}?{UTM}os-referral">Get your referral link<span className="sd-arrow" aria-hidden="true">→</span></a>
    </div>
  </div>
  <div className="sd-ad sd-ad-agency">
    <div className="sd-ad-inner">
      <p className="sd-eyebrow sd-eyebrow-quiet">Done for you</p>
      <p className="sd-ad-title sd-ad-title-sm">Rather have someone run it?</p>
      <p className="sd-ad-copy">We install this system inside your team and run your paid media against it — the same conventions, briefs, and reporting standards you have been reading.</p>
    </div>
    <a className="sd-link" href="{AGENCY_URL}?{UTM}agency">Work with us<span className="sd-arrow" aria-hidden="true">→</span></a>
  </div>
</aside>

{END}"""

# Matches the current block, and the retired snippet-import form so an older
# checkout is cleaned up rather than ending up with both.
BLOCK_RE = re.compile(re.escape(START) + r".*?" + re.escape(END) + r"\n?", re.S)
LEGACY_RE = re.compile(
    r'^import PageEndcap from "/snippets/page-endcap\.mdx";\n\n|\n*^<PageEndcap />\n?',
    re.M,
)


def slugs_in_tabs(node, wanted, inside=False, out=None):
    """Collect every page slug under a tab whose name is in `wanted`."""
    out = [] if out is None else out
    if isinstance(node, list):
        for item in node:
            if isinstance(item, str):
                if inside:
                    out.append(item)
            else:
                slugs_in_tabs(item, wanted, inside, out)
    elif isinstance(node, dict):
        if "tab" in node:
            inside = node["tab"] in wanted
        for value in node.values():
            if isinstance(value, (list, dict)):
                slugs_in_tabs(value, wanted, inside, out)
    return out


def desired(path, keep):
    src = open(path, encoding="utf-8").read()
    wanted = os.path.splitext(path)[0] in keep
    has_endcap = bool(BLOCK_RE.search(src) or LEGACY_RE.search(src))

    # A page that neither has nor wants an endcap is returned byte for byte.
    # Normalizing it would rewrite the ~137 pages that ship without a trailing
    # newline and bury the real change in whitespace noise.
    if not wanted and not has_endcap:
        return src

    stripped = LEGACY_RE.sub("", BLOCK_RE.sub("", src)).rstrip()
    return stripped + "\n\n" + BLOCK + "\n" if wanted else stripped + "\n"


check = "--check" in sys.argv
config = json.load(open("docs.json", encoding="utf-8"))
keep = {s.lstrip("/") for s in slugs_in_tabs(config["navigation"], TABS)}

stale = []
for path in sorted(glob.glob("*.mdx")):
    current = open(path, encoding="utf-8").read()
    target = desired(path, keep)
    if current == target:
        continue
    stale.append(path)
    if not check:
        open(path, "w", encoding="utf-8").write(target)

verb = "out of sync" if check else "synced"
print(f"endcap on {len(keep)} page(s): {', '.join(sorted(keep))}")
print(f"{len(stale)} file(s) {verb}" + (": " + ", ".join(stale) if stale else ""))
sys.exit(1 if (check and stale) else 0)
